# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

HOST: "smtp.mandrillapp.com"
PORT: "587"
MANDRILL_USERNAME: "amar@inquirly.com"
#MANDRILL_API_KEY: "djCf_U9S9FWbH87Nmzfo5w"
MANDRILL_API_KEY: "WVZ17wQGNB8oqasaMKOj0A"
DOMAIN: "inquirly.com"