column_settings:
   categories: "category_types"
   language_count: "language_count"
   business_type_id: "business_type_id"
   questions_count: "questions_count"
   suggestions: "question_suggestions"
   video_photo_count: "video_photo_count"
   qr_share: "qr_share"
   social_share: "social_share"
   embed_share: "embed_share"
   email_count: "email_count"
   tenant_count: "tenant_count"
   customer_records_count: "customer_records_count"
   sms_count: "sms_count"
   call_count: "call_count"
   languages: "languages"
   amount: "amount"
   listener: "listener"

column_resetting:
   categories: "category_types"
   suggestions: "question_suggestions"
   questions_count: "questions_count"
   video_photo_count: "video_photo_count"
   qr_share: "qr_share"
   social_share: "social_share"
   embed_share: "embed_share"
   email_count: "email_count"
   tenant_count: "tenant_count"
   customer_records_count: "customer_records_count"
   sms_count: "sms_count"
   call_count: "call_count"
   languages: "languages"
   listener: "listener"

column_name:
   categories: "questions"
   suggestions: "suggestions"
   questions_count: "questions"
   video_photo_count: "video/photo questions"
   qr_share: "share with QR"
   social_share: "share social"
   embed_share: "embed share"
   email_count: "email count"
   tenant_count: "tenants "
   customer_records_count: "customers"
   sms_count: "sms share"
   call_count: "call share"
   languages: "regional languages"
   listener: "listener"

