account:
 company_settings: 1
 transaction_history: 1
 account_attachment: 2
users/registrations:
 edit: 1
 update: 2
imports:
 csv_template: 2
 create_customer_info: 2
users/omniauth_callbacks:
 linkedin: 2
 facebook: 2
 twitter: 2
downloads:
 download_csv: 2