Individual:
 plan_name: 'Solo'
 business_type_id: 1
 tenant_count: 0
 customer_records_count: 500
 language_count: 1
 questions_count: 180
 question_suggestions: false
 video_photo_count: 120
 qr_share: true
 sms_count: 0
 call_count: 0
 email_count: 6000
 social_share: true
 embed_share: true
 listener: true
 amount: 8000
 from_number: false
 redirect_url: false
 listener_slots: 1
 crawler_slots: 0
 email_alerts: false
Business_small:
 plan_name: 'Business'
 business_type_id: 2
 tenant_count: 3
 customer_records_count: 60000
 language_count: 2
 questions_count: <%=$unlimited%>
 question_suggestions: false
 video_photo_count: 1200
 qr_share: true
 sms_count: 50000
 call_count: 12000
 email_count: 120000
 social_share: true
 embed_share: true
 listener: true
 amount: 72000
 from_number: true
 redirect_url: true
 listener_slots: 5
 crawler_slots: 3
 email_alerts: true
Business_large:
 plan_name: 'Enterprise'
 business_type_id: 3
 tenant_count: 15
 customer_records_count: 600000
 language_count: 4
 questions_count: <%=$unlimited%>
 question_suggestions: true
 video_photo_count: 2400
 qr_share: true
 sms_count: 100000
 call_count: 24000
 email_count: 240000
 social_share: true
 embed_share: true
 listener: true
 amount: 240000
 from_number: true
 redirect_url: true
 listener_slots: 20
 crawler_slots: 5
 email_alerts: true
Trial:
 plan_name: 'Trial'
 business_type_id: 4
 tenant_count: 0
 customer_records_count: 100
 language_count: 2
 questions_count:  10
 question_suggestions: true
 video_photo_count: 5
 qr_share: true
 sms_count: 20
 call_count: 20
 email_count: 500
 social_share: true
 embed_share: true
 listener: true
 amount: 0
 from_number: true
 redirect_url: true
 listener_slots: 1
 crawler_slots: 0
 email_alerts: true