development:
  access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["AWS_BUCKET"] %>
test:
  access_key_id: <%= ENV["TEST_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["TEST_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["AWS_BUCKET"] %>
production:
  access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["AWS_BUCKET"]%>
